### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by bighappyface** [MunGell/wallhack#6]
- [ ] Create a mobile version of eyebrow menu, same look as on .co.uk website

**Comment by bighappyface** [comment]
Shamo,

I like the to-do page but I figured we would do better to setup some issues and a milestone for a 0.1.0 release :smile: 

I added a task-list to this issue that you can augment with additional subtasks. Let me know if this works for you.

**Comment by MunGell** [comment]
Ok, it is fine :)

08 íîÿá. 2013 ã., â 4:19, David Porter notifications@github.com íàïèñàë(à):

**Comment by bighappyface** [comment]
This is looking good to me. We can revisit at a later time.
