### ISSUE TITLE
Harp compile output

### ISSUE THREAD

**Issue by bighappyface** [MunGell/wallhack#8]
We need to determine how to structure and name our files to ensure that running `harp compile` produces clean output to www.

Some concerns include:
- Only producing CSS files necessary for production use
- Only producing HTML files necessary for production use as style guide examples
- Ensuring compilation completes successfully

**Comment by bighappyface** [comment]
@MunGell have you had a chance to run `harp compile`? Currently it is failing on `common.less` and outputting CSS files for `variables.less` and `mixing.less`.

Should we rename `variables.less` and `mixing.less` with a leading underscore to hide them from compilation?

**Comment by MunGell** [comment]
All done in commit 93c990883e86d6589019e548ad98dee1df7fec51
And I agree with the statement in first post.

**Comment by bighappyface** [comment]
The compile output is fantastic and the gh-pages branch is rocking.

http://mungell.github.io/wallhack/

This is good to to. :+1:
